"""Ports used by pure application services."""

from typing import Protocol
from uuid import UUID

from pydantic import SecretStr

from app.domain.models import AnalysisJobView, CvDocumentView, LessonProgress, ProviderConnectionView


class ProgressRepository(Protocol):
    async def list_progress(self, user_id: UUID) -> list[LessonProgress]: ...
    async def replace_progress(self, user_id: UUID, rows: list[LessonProgress]) -> None: ...


class ProviderConnectionRepository(Protocol):
    async def list_connections(self, user_id: UUID) -> list[ProviderConnectionView]: ...
    async def put_connection(self, user_id: UUID, value: ProviderConnectionView) -> None: ...
    async def get_connection(self, user_id: UUID, connection_id: UUID) -> ProviderConnectionView | None: ...
    async def delete_connection(self, user_id: UUID, connection_id: UUID) -> None: ...


class ProviderCredentialRepository(Protocol):
    async def put_credential(self, user_id: UUID, connection_id: UUID, value: SecretStr) -> None: ...
    async def get_credential(self, user_id: UUID, connection_id: UUID) -> SecretStr | None: ...
    async def delete_credential(self, user_id: UUID, connection_id: UUID) -> None: ...


class CvDocumentRepository(Protocol):
    async def put_document(self, user_id: UUID, value: CvDocumentView) -> None: ...
    async def get_document(self, user_id: UUID, document_id: UUID) -> CvDocumentView | None: ...
    async def list_documents(self, user_id: UUID, offset: int, limit: int) -> tuple[list[CvDocumentView], int]: ...
    async def delete_document(self, user_id: UUID, document_id: UUID) -> None: ...


class AnalysisRepository(Protocol):
    async def put_analysis(self, user_id: UUID, value: AnalysisJobView) -> None: ...
    async def list_analyses(self, user_id: UUID, document_id: UUID) -> list[AnalysisJobView]: ...


class ObjectStorage(Protocol):
    async def put_object(self, user_id: UUID, document_id: UUID, value: bytes) -> None: ...
    async def get_object(self, user_id: UUID, document_id: UUID) -> bytes | None: ...
    async def delete_object(self, user_id: UUID, document_id: UUID) -> None: ...
