// Generated by apps/api/scripts/generate_contracts.py. Do not edit.
export const OPENAPI_SHA256 = "ce3e568775d1a7dabf0ed109aed93f73a52774696ae7187d0d5e77c15e7b3ba2";
export type ProviderId = "gemini" | "openai" | "anthropic";
export type DocumentStatus = "uploaded" | "processing" | "complete" | "failed";
export type AnalysisStatus = "pending" | "complete" | "failed";
export interface ApiErrorEnvelope { code: string; message: string; request_id: string; }
export interface ProgressAnswer { value: number; answered_at: string | null; }
export interface LessonProgress { lesson_path: string; answers: Record<string, ProgressAnswer>; completed: boolean; completion_changed_at: string | null; visited_at: string | null; }
export interface ProgressState { lessons: LessonProgress[]; }
