"""Application-service ports used by HTTP adapters and future real adapters."""

from typing import Protocol
from uuid import UUID

from app.domain.models import AnalysisInput, AnalysisJobView, CvDocumentCreate, CvDocumentDetail, CvDocumentView, Page, ProgressState, ProviderConnectionView, SaveProviderConnection


class ProgressService(Protocol):
    async def reconcile(self, user_id: UUID, state: ProgressState) -> ProgressState: ...


class ProviderService(Protocol):
    async def list(self, user_id: UUID) -> list[ProviderConnectionView]: ...
    async def save(self, user_id: UUID, command: SaveProviderConnection) -> ProviderConnectionView: ...
    async def update_model(self, user_id: UUID, item_id: UUID, model: str) -> ProviderConnectionView: ...
    async def delete(self, user_id: UUID, item_id: UUID) -> None: ...


class CvDocumentService(Protocol):
    async def create(self, user_id: UUID, command: CvDocumentCreate) -> CvDocumentView: ...
    async def list(self, user_id: UUID, offset: int, limit: int) -> Page: ...
    async def get(self, user_id: UUID, item_id: UUID) -> CvDocumentView: ...
    async def detail(self, user_id: UUID, item_id: UUID) -> CvDocumentDetail: ...
    async def delete(self, user_id: UUID, item_id: UUID) -> None: ...


class CvAnalysisService(Protocol):
    async def run(self, user_id: UUID, document_id: UUID, model: str, request: AnalysisInput) -> AnalysisJobView: ...
