"""Generate deterministic OpenAPI and the minimal web contract artifact."""

import hashlib
import json
import sys
from pathlib import Path

API_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = API_ROOT.parents[1]
sys.path.insert(0, str(API_ROOT))

from app.main import create_app  # noqa: E402

OPENAPI_PATH = API_ROOT / "openapi.json"
TYPES_PATH = REPOSITORY_ROOT / "apps/web/lib/api/generated.ts"


def render_contracts() -> tuple[str, str]:
    openapi = json.dumps(create_app().openapi(), indent=2, sort_keys=True) + "\n"
    digest = hashlib.sha256(openapi.encode()).hexdigest()
    typescript = f'''// Generated by apps/api/scripts/generate_contracts.py. Do not edit.
export const OPENAPI_SHA256 = "{digest}";
export type ProviderId = "gemini" | "openai" | "anthropic";
export type DocumentStatus = "uploaded" | "processing" | "complete" | "failed";
export type AnalysisStatus = "pending" | "complete" | "failed";
export interface ApiErrorEnvelope {{ code: string; message: string; request_id: string; }}
export interface ProgressAnswer {{ value: number; answered_at: string | null; }}
export interface LessonProgress {{ lesson_path: string; answers: Record<string, ProgressAnswer>; completed: boolean; completion_changed_at: string | null; visited_at: string | null; }}
export interface ProgressState {{ lessons: LessonProgress[]; }}
'''
    return openapi, typescript


if __name__ == "__main__":
    openapi, typescript = render_contracts()
    OPENAPI_PATH.write_text(openapi, encoding="utf-8")
    TYPES_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPES_PATH.write_text(typescript, encoding="utf-8")
